### ISSUE TITLE
Could you please help me add plugin http.filter?

### ISSUE THREAD

**Issue by Noahsarker** [tmpim/casket#14]
the plugin source ,https://github.com/echocat/caddy-filter
I can't build..

**Comment by Lustyn** [comment]
Getting Caddy V1 plugins working with Casket simply requires that you make a custom build including the plugin.

[See this comment for reference](https://github.com/tmpim/casket/issues/6#issuecomment-706574366). If you have issues with Casket itself that are not related to the plugin code, feel free to open up a separate issue for that.
