### ISSUE TITLE
chore: upgrade certmagic

### ISSUE THREAD

**Issue by Lustyn** [tmpim/casket#19]
Our certmagic version is stale since Dec 2020, Let's Encrypt will be making changes soon that mean we should prioritize getting these changes out in a new release ASAP.

We can either:
 - Merge upstream changes into our certmagic fork, or:
 - Switch to mainline certmagic.

**Comment by Lemmmy** [comment]
Does our certmagic have any changes other than [only retrying once](https://github.com/tmpim/certmagic/commit/874aeb06dd516750c63f4117ee7c1f7714c0d743)? If it was easier, I wouldn't mind losing this functionality in favor of switching back to mainline certmagic. 

It _is_ handy to prevent getting rate limited from LE, but really these situations should just be avoided in the first place, and I think most people who are running enough sites to risk being rate limited now know how to handle it (or are just using self-signed).
