### ISSUE TITLE
docs: dedicated documentation site

### ISSUE THREAD

**Issue by Lemmmy** [tmpim/casket#21]
The new [tryfiles plugin](https://github.com/tmpim/casket/blob/1bedd5ec6b39f8c995ced02f335d0b07faae0290/caskethttp/tryfiles/tryfiles.go) (#15) is not documented on the [website](https://caddy.its-em.ma/).

**Comment by Lustyn** [comment]
I think this is a larger story to do with creating our own docs, which is probably more realistic than digging up and forking Caddy v1's since deleted documentation. The difference to Casket's current iteration vs [Emma's rehosted docs](https://caddy.its-em.ma/) is quite minimal all things considered.

**Comment by Lemmmy** [comment]
I'm hoping to start tackling this over the weekend. Planning to try to either use the old 8-year-old copies of the markdown docs, or convert the html to mdx (more likely) and go from there, in a vitepress site probably

**Comment by Lemmmy** [comment]
Casket docs are now up at [docs.casketserver.com](https://docs.casketserver.com). Some changes have been made already, but the rest of the new features will be documented in due course. [casket.tmpim.pw](https://casket.tmpim.pw) now redirects here (this redirect may be cached for a while if you used it before).

The repository to contribute to is now public: [tmpim/casket-docs](https://github.com/tmpim/casket-docs).

The Caddy v1 docs mirror is still available at [caddy.its-em.ma](https://caddy.its-em.ma). [v1.casketserver.com](https://v1.casketserver.com) will redirect to these.
