### ISSUE TITLE
Need GRPC proxy support

### ISSUE THREAD

**Issue by Joyace** [tmpim/casket#22]
Just like caddy v2, grpc ports can be proxied.

```
data.example.com:443 {
    reverse_proxy {
        to localhost:5555
        transport http {
            versions h2c 2
        }
    }
}
```

**Comment by Lustyn** [comment]
Casket is not realistically taking feature requests at this time. This should either be opened in the form of a discussion (theorizing the implementation) or a pull request supporting the feature.
