### ISSUE TITLE
Hello，Where can I download the release of all plugins?

### ISSUE THREAD

**Issue by Joyace** [tmpim/casket#6]
Hello~

Where can I download the release of all plugins?

**Comment by Joyace** [comment]
I need webdav and filebrowser.

**Comment by Lemmmy** [comment]
The builds on the [releases page](https://github.com/tmpim/casket/releases) contain all the built-in plugins by default. For a custom configuration, you can build yourself. We may have a website soon.

`./casket -plugins`:

```
Server types:
  http

Casketfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.chuieauth
  http.cors
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.prometheus
  http.proxy
  http.push
  http.ratelimit
  http.realip
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  on
  tls
  tls.cluster.file
  tls.dns.azure
  tls.dns.cloudflare
  tls.dns.digitalocean
  tls.dns.dnsimple
  tls.dns.duckdns
  tls.dns.dyn
  tls.dns.godaddy
  tls.dns.googlecloud
  tls.dns.httpreq
  tls.dns.lightsail
  tls.dns.linode
  tls.dns.linodev4
  tls.dns.namecheap
  tls.dns.namedotcom
  tls.dns.ovh
  tls.dns.rackspace
  tls.dns.rfc2136
  tls.dns.route53
  tls.dns.vultr
```

**Comment by Joyace** [comment]
Looking forward to your website.

How to build a release that includes webdav?

**Comment by emmachase** [comment]
As @Lemmmy stated, all of the plugins that were recognized as "official" by caddy are included in the release builds by default.
This includes webdav and filebrowser:
https://github.com/tmpim/casket/blob/c517c999547ba144b9c25f94530c1f99a28746ac/caskethttp/httpserver/plugin.go#L686-L687

So just downloading the [latest release](https://github.com/tmpim/casket/releases/latest) should get you what you need.

**Comment by emmachase** [comment]
You can add plugins to build with by including their module paths in `casket/casketmain/plugins.go`

For example:
```go
import (
	_ "github.com/hacdias/caddy-webdav"

	_ "github.com/tmpim/casket-plugins/chuieauth"
	....
```

**Comment by emmachase** [comment]
However, the caddy version of webdav requires caddy not casket. Please use the following `plugins.go`
```go
import (
	_ "github.com/emmachase/casket-webdav"

	_ "github.com/tmpim/casket-plugins/chuieauth"
	....
```

@Joyace Please let me know if this works for you.

**Comment by emmachase** [comment]
And as for filebrowser, the caddy plugin is no longer supported (see https://github.com/filebrowser/filebrowser/issues/723). However, as noted in that issue, it is trivial to use filebrowser as it works today by using the `proxy` directive.

**Comment by Joyace** [comment]
Ok i try it, thank you very much.

**Comment by Joyace** [comment]
I encountered an error while building：

```
root@vps-c570e93e:~/casket# go build
commands.go:22:2: cannot find package "github.com/flynn/go-shlex" in any of:
        /usr/lib/go-1.7/src/github.com/flynn/go-shlex (from $GOROOT)
        ($GOPATH not set)
casket.go:46:2: cannot find package "github.com/tmpim/casket/casketfile" in any of:
        /usr/lib/go-1.7/src/github.com/tmpim/casket/casketfile (from $GOROOT)
        ($GOPATH not set)
casket.go:47:2: cannot find package "github.com/tmpim/casket/telemetry" in any of:
        /usr/lib/go-1.7/src/github.com/tmpim/casket/telemetry (from $GOROOT)
        ($GOPATH not set)
```

**Comment by emmachase** [comment]
The following build steps worked for me with a fresh ubuntu vm:
```
apt install golang-go git
git clone https://github.com/tmpim/casket.git
cd casket
go build
```

If I had to guess, it is likely because you are using go1.7 (as evidenced from your logs), although I'm not sure why that would interfere with module resolution.

**Comment by Joyace** [comment]
Yes, I updated golang, and now there is no output after running go build. I don't know if the build is complete, nor can I find the executable file.
```
root@vps-c570e93e:~/casket# go build
go: downloading github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/google/uuid v1.1.1
root@vps-c570e93e:~/casket# go build
root@vps-c570e93e:~/casket# ls
assets.go            caskethttp        dist         README.md            telemetry
assets_test.go       casket_test.go    go.mod       rlimit_nonposix.go   upgrade.go
azure-pipelines.yml  caskettls         go.sum       rlimit_posix.go
casket               commands.go       LICENSE.txt  sigtrap.go
casketfile           commands_test.go  onevent      sigtrap_nonposix.go
casket.go            controller.go     plugins.go   sigtrap_posix.go
```

**Comment by emmachase** [comment]
To build the main executable you should use
```go14 build -o build/casket ./casket```

**Comment by Joyace** [comment]
The file was generated this time, but the file size seems to be incorrect and it cannot run normally.

```
root@vps-c570e93e:~/casket# go build -o /root/build/casket
root@vps-c570e93e:~/casket# cd /root/casket
root@vps-c570e93e:~/casket# cd /root/build
root@vps-c570e93e:~/build# ll
-bash: ll: command not found
root@vps-c570e93e:~/build# ls -l
total 532
-rw-r--r-- 1 root root 543270 Oct 10 17:27 casket
root@vps-c570e93e:~/build# chmod 777 casket
root@vps-c570e93e:~/build# ./casket -h
./casket: line 1: syntax error near unexpected token `newline'
./casket: line 1: `!<arch>'
```

**Comment by emmachase** [comment]
The `./casket` in the build command is necessary.

**Comment by Joyace** [comment]
I'm very sorry, I am a rookie, I have troubled you for a long time, maybe you can add the webdav plugin in the distribution by default, I believe some people need it.

**Comment by Joyace** [comment]
It is runing now.thx
```
go: downloading github.com/marten-seemann/chacha20 v0.2.0
go: downloading golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.1.0
go: downloading github.com/cenkalti/backoff/v3 v3.0.0
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/marten-seemann/qtls v0.4.1
go: downloading github.com/linode/linodego v0.10.0
go: downloading github.com/naoina/toml v0.1.1
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading gopkg.in/resty.v1 v1.12.0
go: downloading github.com/Azure/go-autorest/autorest/validation v0.1.0
go: found github.com/emmachase/casket-webdav in github.com/emmachase/casket-webdav v1.1.2
go: downloading github.com/hacdias/webdav/v3 v3.0.0
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading gopkg.in/yaml.v2 v2.2.5
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.9.0
```

**Comment by emmachase** [comment]
Here is a link to the latest version with webdav: https://its-em.ma/casket-1-1-5-with-webdav
I'm not sure that it is warranted to include it by default (@1lann what do you think?).
It is possible that in the future we may have a build generator like caddy had where you could generate a build with certain plugins.

**Comment by emmachase** [comment]
For right now however, I do think there could be better documentation in the readme for building.

**Comment by Lemmmy** [comment]
FYI @Joyace we have a mirror of the v1 docs hosted on https://casket.tmpim.pw, though most of the other features on the site haven't been recreated yet
